apiVersion: v1
kind: Service
metadata:
  name: dms
  namespace: namespace-workflow-1731757743136
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: dms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080